language: julia

arch:
  - amd64

-os:
  - linux

jobs:
  include:
    - name: "Legacy, Julia 1.0"
      julia: 1.0
    - name: "MASTER AND TAGS"
      julia: 1.5
    - name: "OSX, Julia 1.5"
      julia: 1.5
      os: osx
    - name: "Julia nightly"
      julia: nightly
    # - name: "ARM64, Julia 1.4"
    #   if: NOT branch =~ ^release.*$
    #   arch: arm64
    #   julia: 1.4
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx
    # - arch: arm64

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("KernelDensityEstimatePlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
