language: julia

arch:
  - amd64

os:
  - linux

julia:
  - 1.5

jobs:
  include:
    - name: "Legacy, Julia 1.0"
      julia: 1.0
    - name: "MASTER AND TAGS"
    - name: "Julia nightly"
      julia: nightly
    - name: "OSX"
      os: osx
    - name: "ARM64"
      arch: arm64
      # if: NOT branch =~ ^release.*$
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx
    - arch: arm64

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("KernelDensityEstimatePlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
