name = "KernelDensityEstimatePlotting"
uuid = "c43967c8-f634-5d24-8eab-2867546b366b"
keywords = ["KDE", "SLAM", "plotting", "2D", "robotics", "navigation"]
desc = "Visualization tools for the KernelDensityEstimate.jl package."
version = "0.1.8"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
KernelDensityEstimate = "2472808a-b354-52ea-a80e-1658a3c6056d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Colors = "0.11, 0.12"
Compose = "0.8, 0.9"
DocStringExtensions = "0.8, 0.9"
Gadfly = "1"
KernelDensityEstimate = "0.5"
julia = "1.6"

[extras]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cairo", "Test"]
